[2022-10-07T21:22:17.411+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-06T00:00:00+00:00 [queued]>
[2022-10-07T21:22:17.571+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-06T00:00:00+00:00 [queued]>
[2022-10-07T21:22:17.581+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T21:22:17.585+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-07T21:22:17.596+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T21:22:17.885+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): create_table_in_database> on 2022-10-06 00:00:00+00:00
[2022-10-07T21:22:17.909+0000] {standard_task_runner.py:54} INFO - Started process 383 to run task
[2022-10-07T21:22:17.934+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Tweets_Dag', 'create_table_in_database', 'scheduled__2022-10-06T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/TweetsDag.py', '--cfg-path', '/tmp/tmpxact8vk1']
[2022-10-07T21:22:17.948+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask create_table_in_database
[2022-10-07T21:22:17.984+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/TweetsDag.py
[2022-10-07T21:22:18.856+0000] {task_command.py:384} INFO - Running <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-06T00:00:00+00:00 [running]> on host ffc3975ad4f7
[2022-10-07T21:22:19.616+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Tweets_Dag
AIRFLOW_CTX_TASK_ID=create_table_in_database
AIRFLOW_CTX_EXECUTION_DATE=2022-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-06T00:00:00+00:00
[2022-10-07T21:22:19.631+0000] {mysql.py:84} INFO - Executing: CREATE TABLE IF NOT EXIST tweets(user varchar(255),date DATE,content varchar(255))
[2022-10-07T21:22:19.908+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 165, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db` isn't defined
[2022-10-07T21:22:19.960+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=Tweets_Dag, task_id=create_table_in_database, execution_date=20221006T000000, start_date=20221007T212217, end_date=20221007T212219
[2022-10-07T21:22:20.049+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task create_table_in_database (The conn_id `***_db` isn't defined; 383)
[2022-10-07T21:22:20.111+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-07T21:22:20.383+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
