[2022-10-07T21:22:17.454+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-05T00:00:00+00:00 [queued]>
[2022-10-07T21:22:17.591+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-05T00:00:00+00:00 [queued]>
[2022-10-07T21:22:17.596+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T21:22:17.611+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-07T21:22:17.670+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T21:22:17.940+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): create_table_in_database> on 2022-10-05 00:00:00+00:00
[2022-10-07T21:22:18.006+0000] {standard_task_runner.py:54} INFO - Started process 384 to run task
[2022-10-07T21:22:18.058+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Tweets_Dag', 'create_table_in_database', 'scheduled__2022-10-05T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/TweetsDag.py', '--cfg-path', '/tmp/tmp_9acf6l5']
[2022-10-07T21:22:18.066+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_table_in_database
[2022-10-07T21:22:18.077+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/TweetsDag.py
[2022-10-07T21:22:18.998+0000] {task_command.py:384} INFO - Running <TaskInstance: Tweets_Dag.create_table_in_database scheduled__2022-10-05T00:00:00+00:00 [running]> on host ffc3975ad4f7
[2022-10-07T21:22:19.891+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Tweets_Dag
AIRFLOW_CTX_TASK_ID=create_table_in_database
AIRFLOW_CTX_EXECUTION_DATE=2022-10-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-05T00:00:00+00:00
[2022-10-07T21:22:19.906+0000] {mysql.py:84} INFO - Executing: CREATE TABLE IF NOT EXIST tweets(user varchar(255),date DATE,content varchar(255))
[2022-10-07T21:22:20.053+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 165, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db` isn't defined
[2022-10-07T21:22:20.076+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=Tweets_Dag, task_id=create_table_in_database, execution_date=20221005T000000, start_date=20221007T212217, end_date=20221007T212220
[2022-10-07T21:22:20.207+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task create_table_in_database (The conn_id `***_db` isn't defined; 384)
[2022-10-07T21:22:20.308+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-07T21:22:20.502+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
