[2022-10-08T08:23:33.347+0000] {processor.py:156} INFO - Started process (PID=62) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:23:33.355+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:23:33.368+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:23:33.358+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:23:35.599+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:23:35.504+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:23:35.634+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:23:36.727+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 3.400 seconds
[2022-10-08T08:24:06.996+0000] {processor.py:156} INFO - Started process (PID=74) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:07.011+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:24:07.022+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:24:07.021+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:09.119+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:24:09.054+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:24:09.134+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:09.265+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.282 seconds
[2022-10-08T08:24:40.726+0000] {processor.py:156} INFO - Started process (PID=94) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:40.789+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:24:40.806+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:24:40.805+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:45.040+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:24:44.960+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:24:45.077+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:24:45.340+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 4.714 seconds
[2022-10-08T08:25:16.304+0000] {processor.py:156} INFO - Started process (PID=114) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:25:16.346+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:25:16.356+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:25:16.356+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:25:26.584+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:25:26.278+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:25:27.083+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:25:29.495+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 13.225 seconds
[2022-10-08T08:26:01.367+0000] {processor.py:156} INFO - Started process (PID=133) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:01.405+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:26:01.408+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:26:01.407+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:03.622+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:26:03.510+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:26:03.793+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:05.076+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 3.743 seconds
[2022-10-08T08:26:36.541+0000] {processor.py:156} INFO - Started process (PID=152) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:36.598+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:26:36.627+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:26:36.623+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:38.396+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:26:38.354+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:26:38.406+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:26:38.616+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.123 seconds
[2022-10-08T08:27:09.680+0000] {processor.py:156} INFO - Started process (PID=162) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:09.692+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:27:09.699+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:27:09.698+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:10.195+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:27:10.172+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:27:10.205+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:10.403+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.769 seconds
[2022-10-08T08:27:41.921+0000] {processor.py:156} INFO - Started process (PID=183) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:42.000+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:27:42.006+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:27:42.005+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:43.270+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:27:43.099+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:27:43.342+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:27:43.720+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.862 seconds
[2022-10-08T08:28:14.659+0000] {processor.py:156} INFO - Started process (PID=192) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:14.701+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:28:14.703+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:28:14.703+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:16.074+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:28:15.958+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:28:16.103+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:16.354+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.762 seconds
[2022-10-08T08:28:46.655+0000] {processor.py:156} INFO - Started process (PID=211) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:46.683+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:28:46.736+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:28:46.715+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:47.985+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:28:47.935+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:28:47.997+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:28:48.288+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.685 seconds
[2022-10-08T08:29:18.511+0000] {processor.py:156} INFO - Started process (PID=229) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:18.521+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:29:18.523+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:29:18.523+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:19.054+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:29:19.044+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:29:19.057+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:19.110+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.626 seconds
[2022-10-08T08:29:49.608+0000] {processor.py:156} INFO - Started process (PID=247) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:49.610+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:29:49.612+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:29:49.612+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:49.868+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:29:49.853+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:29:49.872+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:29:49.974+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.377 seconds
[2022-10-08T08:30:20.082+0000] {processor.py:156} INFO - Started process (PID=266) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:20.084+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:30:20.094+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:30:20.093+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:20.369+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:30:20.359+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:30:20.374+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:20.501+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.430 seconds
[2022-10-08T08:30:50.725+0000] {processor.py:156} INFO - Started process (PID=287) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:50.728+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:30:50.731+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:30:50.730+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:50.881+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:30:50.871+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:30:50.885+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:30:50.917+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.200 seconds
[2022-10-08T08:31:21.123+0000] {processor.py:156} INFO - Started process (PID=306) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:21.126+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:31:21.132+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:31:21.131+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:21.286+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:31:21.276+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:31:21.290+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:21.323+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.206 seconds
[2022-10-08T08:31:51.706+0000] {processor.py:156} INFO - Started process (PID=325) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:51.708+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:31:51.710+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:31:51.709+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:51.927+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:31:51.916+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:31:51.930+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:31:51.973+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.274 seconds
[2022-10-08T08:32:22.173+0000] {processor.py:156} INFO - Started process (PID=344) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:22.184+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:32:22.188+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:32:22.187+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:22.604+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:32:22.571+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:32:22.634+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:22.705+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.550 seconds
[2022-10-08T08:32:52.881+0000] {processor.py:156} INFO - Started process (PID=365) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:52.886+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:32:52.891+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:32:52.890+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:53.062+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:32:53.054+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:32:53.064+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:32:53.099+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.224 seconds
[2022-10-08T08:33:23.190+0000] {processor.py:156} INFO - Started process (PID=393) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:23.192+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:33:23.194+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:33:23.194+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:23.357+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:33:23.346+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:33:23.360+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:23.431+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.248 seconds
[2022-10-08T08:33:53.927+0000] {processor.py:156} INFO - Started process (PID=415) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:53.929+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:33:53.930+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:33:53.930+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:54.103+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:33:54.088+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:33:54.107+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:33:54.155+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.233 seconds
[2022-10-08T08:34:24.264+0000] {processor.py:156} INFO - Started process (PID=434) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:24.267+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:34:24.270+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:34:24.270+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:24.416+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:34:24.408+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:34:24.419+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:24.453+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.200 seconds
[2022-10-08T08:34:54.823+0000] {processor.py:156} INFO - Started process (PID=453) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:54.825+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08T08:34:54.827+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:34:54.826+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:55.005+0000] {logging_mixin.py:117} INFO - [2022-10-08T08:34:54.990+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 7, in <module>
    from FetchTweets import Fetchtweets
  File "/opt/airflow/dags/FetchTweets.py", line 1, in <module>
    import snscrape.modules.twitter as sntwitter
ModuleNotFoundError: No module named 'snscrape'
[2022-10-08T08:34:55.008+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08T08:34:55.043+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.226 seconds
[2022-10-08 08:36:00,076] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:00,079] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:36:00,089] {logging_mixin.py:109} INFO - [2022-10-08 08:36:00,089] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:07,512] {logging_mixin.py:109} INFO - [2022-10-08 08:36:07,493] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:36:07,543] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:07,588] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 7.518 seconds
[2022-10-08 08:36:38,499] {processor.py:163} INFO - Started process (PID=61) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:38,523] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:36:38,543] {logging_mixin.py:109} INFO - [2022-10-08 08:36:38,542] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:49,595] {logging_mixin.py:109} INFO - [2022-10-08 08:36:49,481] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:36:49,659] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:36:49,769] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 11.289 seconds
[2022-10-08 08:37:20,496] {processor.py:163} INFO - Started process (PID=82) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:20,507] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:37:20,510] {logging_mixin.py:109} INFO - [2022-10-08 08:37:20,510] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:22,764] {logging_mixin.py:109} INFO - [2022-10-08 08:37:22,752] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:37:22,784] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:22,802] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.317 seconds
[2022-10-08 08:37:52,968] {processor.py:163} INFO - Started process (PID=104) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:52,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:37:52,972] {logging_mixin.py:109} INFO - [2022-10-08 08:37:52,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:54,515] {logging_mixin.py:109} INFO - [2022-10-08 08:37:54,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:37:54,535] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:37:54,549] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.586 seconds
[2022-10-08 08:38:24,747] {processor.py:163} INFO - Started process (PID=125) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:24,750] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:38:24,752] {logging_mixin.py:109} INFO - [2022-10-08 08:38:24,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:26,238] {logging_mixin.py:109} INFO - [2022-10-08 08:38:26,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:38:26,257] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:26,272] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.531 seconds
[2022-10-08 08:38:56,366] {processor.py:163} INFO - Started process (PID=148) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:56,368] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:38:56,369] {logging_mixin.py:109} INFO - [2022-10-08 08:38:56,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:57,815] {logging_mixin.py:109} INFO - [2022-10-08 08:38:57,803] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:38:57,835] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:38:57,852] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.490 seconds
[2022-10-08 08:39:28,004] {processor.py:163} INFO - Started process (PID=170) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:39:28,006] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:39:28,007] {logging_mixin.py:109} INFO - [2022-10-08 08:39:28,007] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:39:29,389] {logging_mixin.py:109} INFO - [2022-10-08 08:39:29,378] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:39:29,410] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:39:29,424] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.425 seconds
[2022-10-08 08:39:59,618] {processor.py:163} INFO - Started process (PID=199) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:39:59,621] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:39:59,622] {logging_mixin.py:109} INFO - [2022-10-08 08:39:59,622] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:02,300] {logging_mixin.py:109} INFO - [2022-10-08 08:40:02,288] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:40:02,345] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:02,388] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.776 seconds
[2022-10-08 08:40:07,672] {processor.py:163} INFO - Started process (PID=205) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:07,674] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:40:07,676] {logging_mixin.py:109} INFO - [2022-10-08 08:40:07,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:09,651] {logging_mixin.py:109} INFO - [2022-10-08 08:40:09,640] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/TweetsDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/TweetsDag.py", line 8, in <module>
    from Preprocessing import clean_tweets
  File "/opt/airflow/dags/Preprocessing.py", line 7, in <module>
    stw=stopwords.words('english')
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/airflow/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/home/airflow/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
[2022-10-08 08:40:09,715] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:09,728] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.063 seconds
[2022-10-08 08:40:16,774] {processor.py:163} INFO - Started process (PID=210) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:16,777] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:40:16,778] {logging_mixin.py:109} INFO - [2022-10-08 08:40:16,778] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:17,890] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:19,268] {logging_mixin.py:109} INFO - [2022-10-08 08:40:19,267] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:40:19,308] {logging_mixin.py:109} INFO - [2022-10-08 08:40:19,308] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:40:19,345] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.580 seconds
[2022-10-08 08:40:49,586] {processor.py:163} INFO - Started process (PID=232) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:49,589] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:40:49,591] {logging_mixin.py:109} INFO - [2022-10-08 08:40:49,591] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:51,041] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:40:51,057] {logging_mixin.py:109} INFO - [2022-10-08 08:40:51,056] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:40:51,099] {logging_mixin.py:109} INFO - [2022-10-08 08:40:51,098] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:40:51,124] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.546 seconds
[2022-10-08 08:41:21,303] {processor.py:163} INFO - Started process (PID=253) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:21,306] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:41:21,308] {logging_mixin.py:109} INFO - [2022-10-08 08:41:21,307] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:22,470] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:22,483] {logging_mixin.py:109} INFO - [2022-10-08 08:41:22,483] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:41:22,504] {logging_mixin.py:109} INFO - [2022-10-08 08:41:22,504] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:41:22,517] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.221 seconds
[2022-10-08 08:41:52,704] {processor.py:163} INFO - Started process (PID=275) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:52,707] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:41:52,709] {logging_mixin.py:109} INFO - [2022-10-08 08:41:52,708] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:54,037] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:41:54,055] {logging_mixin.py:109} INFO - [2022-10-08 08:41:54,054] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:41:54,084] {logging_mixin.py:109} INFO - [2022-10-08 08:41:54,084] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:41:54,125] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.428 seconds
[2022-10-08 08:42:24,379] {processor.py:163} INFO - Started process (PID=296) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:24,382] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:42:24,385] {logging_mixin.py:109} INFO - [2022-10-08 08:42:24,384] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:25,801] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:25,814] {logging_mixin.py:109} INFO - [2022-10-08 08:42:25,813] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:42:25,835] {logging_mixin.py:109} INFO - [2022-10-08 08:42:25,835] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:42:25,850] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.478 seconds
[2022-10-08 08:42:56,062] {processor.py:163} INFO - Started process (PID=317) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:56,064] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:42:56,065] {logging_mixin.py:109} INFO - [2022-10-08 08:42:56,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:57,114] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:42:57,126] {logging_mixin.py:109} INFO - [2022-10-08 08:42:57,125] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:42:57,147] {logging_mixin.py:109} INFO - [2022-10-08 08:42:57,146] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:42:57,162] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.105 seconds
[2022-10-08 08:43:27,293] {processor.py:163} INFO - Started process (PID=338) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:43:27,296] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:43:27,300] {logging_mixin.py:109} INFO - [2022-10-08 08:43:27,300] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:43:28,583] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:43:28,601] {logging_mixin.py:109} INFO - [2022-10-08 08:43:28,600] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:43:28,629] {logging_mixin.py:109} INFO - [2022-10-08 08:43:28,629] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:43:28,648] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.362 seconds
[2022-10-08 08:43:58,868] {processor.py:163} INFO - Started process (PID=361) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:43:58,870] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:43:58,872] {logging_mixin.py:109} INFO - [2022-10-08 08:43:58,872] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:44:00,373] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:44:00,405] {logging_mixin.py:109} INFO - [2022-10-08 08:44:00,404] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:44:00,462] {logging_mixin.py:109} INFO - [2022-10-08 08:44:00,462] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:44:00,502] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.640 seconds
[2022-10-08 08:44:30,857] {processor.py:163} INFO - Started process (PID=382) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:44:30,860] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:44:30,862] {logging_mixin.py:109} INFO - [2022-10-08 08:44:30,861] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:44:31,905] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:44:31,935] {logging_mixin.py:109} INFO - [2022-10-08 08:44:31,934] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:44:31,977] {logging_mixin.py:109} INFO - [2022-10-08 08:44:31,977] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:44:31,996] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.144 seconds
[2022-10-08 08:45:02,185] {processor.py:163} INFO - Started process (PID=404) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:02,187] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:45:02,189] {logging_mixin.py:109} INFO - [2022-10-08 08:45:02,188] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:03,132] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:03,145] {logging_mixin.py:109} INFO - [2022-10-08 08:45:03,145] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:45:03,165] {logging_mixin.py:109} INFO - [2022-10-08 08:45:03,165] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:45:03,180] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 0.999 seconds
[2022-10-08 08:45:33,617] {processor.py:163} INFO - Started process (PID=425) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:33,626] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:45:33,628] {logging_mixin.py:109} INFO - [2022-10-08 08:45:33,628] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:38,715] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:45:38,775] {logging_mixin.py:109} INFO - [2022-10-08 08:45:38,774] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:45:38,903] {logging_mixin.py:109} INFO - [2022-10-08 08:45:38,902] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:45:39,008] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 5.405 seconds
[2022-10-08 08:46:09,237] {processor.py:163} INFO - Started process (PID=447) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:09,240] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:46:09,241] {logging_mixin.py:109} INFO - [2022-10-08 08:46:09,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:11,025] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:11,048] {logging_mixin.py:109} INFO - [2022-10-08 08:46:11,047] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:46:11,074] {logging_mixin.py:109} INFO - [2022-10-08 08:46:11,073] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:46:11,090] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.859 seconds
[2022-10-08 08:46:41,358] {processor.py:163} INFO - Started process (PID=468) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:41,360] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:46:41,361] {logging_mixin.py:109} INFO - [2022-10-08 08:46:41,361] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:42,828] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:46:42,841] {logging_mixin.py:109} INFO - [2022-10-08 08:46:42,841] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:46:42,867] {logging_mixin.py:109} INFO - [2022-10-08 08:46:42,867] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:46:42,884] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.532 seconds
[2022-10-08 08:47:13,044] {processor.py:163} INFO - Started process (PID=489) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:13,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:47:13,048] {logging_mixin.py:109} INFO - [2022-10-08 08:47:13,048] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:14,399] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:14,418] {logging_mixin.py:109} INFO - [2022-10-08 08:47:14,417] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:47:14,450] {logging_mixin.py:109} INFO - [2022-10-08 08:47:14,450] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:47:14,469] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.430 seconds
[2022-10-08 08:47:44,655] {processor.py:163} INFO - Started process (PID=509) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:44,658] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:47:44,659] {logging_mixin.py:109} INFO - [2022-10-08 08:47:44,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:46,058] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:47:46,071] {logging_mixin.py:109} INFO - [2022-10-08 08:47:46,070] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:47:46,095] {logging_mixin.py:109} INFO - [2022-10-08 08:47:46,095] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:47:46,114] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.463 seconds
[2022-10-08 08:48:16,321] {processor.py:163} INFO - Started process (PID=538) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:16,332] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:48:16,342] {logging_mixin.py:109} INFO - [2022-10-08 08:48:16,341] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:18,106] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:18,128] {logging_mixin.py:109} INFO - [2022-10-08 08:48:18,127] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:48:18,176] {logging_mixin.py:109} INFO - [2022-10-08 08:48:18,176] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:48:18,213] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.901 seconds
[2022-10-08 08:48:22,065] {processor.py:163} INFO - Started process (PID=544) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:22,069] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:48:22,071] {logging_mixin.py:109} INFO - [2022-10-08 08:48:22,071] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:23,404] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:23,735] {logging_mixin.py:109} INFO - [2022-10-08 08:48:23,735] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:48:23,758] {logging_mixin.py:109} INFO - [2022-10-08 08:48:23,757] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:48:23,783] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.762 seconds
[2022-10-08 08:48:24,300] {processor.py:163} INFO - Started process (PID=549) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:24,302] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:48:24,304] {logging_mixin.py:109} INFO - [2022-10-08 08:48:24,304] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:26,073] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:26,081] {logging_mixin.py:109} INFO - [2022-10-08 08:48:26,080] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:48:26,127] {logging_mixin.py:109} INFO - [2022-10-08 08:48:26,126] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:48:26,161] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.867 seconds
[2022-10-08 08:48:56,545] {processor.py:163} INFO - Started process (PID=570) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:56,549] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:48:56,550] {logging_mixin.py:109} INFO - [2022-10-08 08:48:56,550] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:57,690] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:48:57,703] {logging_mixin.py:109} INFO - [2022-10-08 08:48:57,702] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:48:57,724] {logging_mixin.py:109} INFO - [2022-10-08 08:48:57,723] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:48:57,739] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.200 seconds
[2022-10-08 08:49:27,916] {processor.py:163} INFO - Started process (PID=591) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:49:27,919] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:49:27,920] {logging_mixin.py:109} INFO - [2022-10-08 08:49:27,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:49:29,050] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:49:29,065] {logging_mixin.py:109} INFO - [2022-10-08 08:49:29,064] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:49:29,094] {logging_mixin.py:109} INFO - [2022-10-08 08:49:29,093] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:49:29,110] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.199 seconds
[2022-10-08 08:49:59,173] {processor.py:163} INFO - Started process (PID=613) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:49:59,175] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:49:59,176] {logging_mixin.py:109} INFO - [2022-10-08 08:49:59,176] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:50:01,133] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:50:01,177] {logging_mixin.py:109} INFO - [2022-10-08 08:50:01,177] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:50:01,208] {logging_mixin.py:109} INFO - [2022-10-08 08:50:01,208] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:50:01,226] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.058 seconds
[2022-10-08 08:50:31,423] {processor.py:163} INFO - Started process (PID=634) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:50:31,425] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:50:31,426] {logging_mixin.py:109} INFO - [2022-10-08 08:50:31,426] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:50:32,730] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:50:32,749] {logging_mixin.py:109} INFO - [2022-10-08 08:50:32,748] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:50:32,776] {logging_mixin.py:109} INFO - [2022-10-08 08:50:32,776] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:50:32,794] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.377 seconds
[2022-10-08 08:51:03,321] {processor.py:163} INFO - Started process (PID=655) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:03,325] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:51:03,327] {logging_mixin.py:109} INFO - [2022-10-08 08:51:03,327] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:05,176] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:05,194] {logging_mixin.py:109} INFO - [2022-10-08 08:51:05,193] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:51:05,229] {logging_mixin.py:109} INFO - [2022-10-08 08:51:05,229] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:51:05,258] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.965 seconds
[2022-10-08 08:51:35,495] {processor.py:163} INFO - Started process (PID=676) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:35,498] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:51:35,500] {logging_mixin.py:109} INFO - [2022-10-08 08:51:35,500] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:36,591] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:51:36,605] {logging_mixin.py:109} INFO - [2022-10-08 08:51:36,605] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:51:36,628] {logging_mixin.py:109} INFO - [2022-10-08 08:51:36,627] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:51:36,647] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.158 seconds
[2022-10-08 08:52:06,979] {processor.py:163} INFO - Started process (PID=698) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:06,981] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:52:06,983] {logging_mixin.py:109} INFO - [2022-10-08 08:52:06,983] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:08,746] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:08,761] {logging_mixin.py:109} INFO - [2022-10-08 08:52:08,760] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:52:08,790] {logging_mixin.py:109} INFO - [2022-10-08 08:52:08,789] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:52:08,810] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.822 seconds
[2022-10-08 08:52:39,252] {processor.py:163} INFO - Started process (PID=719) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:39,266] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:52:39,268] {logging_mixin.py:109} INFO - [2022-10-08 08:52:39,267] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:41,279] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:52:41,336] {logging_mixin.py:109} INFO - [2022-10-08 08:52:41,335] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:52:41,406] {logging_mixin.py:109} INFO - [2022-10-08 08:52:41,406] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:52:41,507] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 2.263 seconds
[2022-10-08 08:53:11,680] {processor.py:163} INFO - Started process (PID=740) to work on /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:53:11,682] {processor.py:642} INFO - Processing file /opt/airflow/dags/TweetsDag.py for tasks to queue
[2022-10-08 08:53:11,684] {logging_mixin.py:109} INFO - [2022-10-08 08:53:11,684] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:53:13,375] {processor.py:654} INFO - DAG(s) dict_keys(['Tweets_Dag']) retrieved from /opt/airflow/dags/TweetsDag.py
[2022-10-08 08:53:13,394] {logging_mixin.py:109} INFO - [2022-10-08 08:53:13,394] {dag.py:2396} INFO - Sync 1 DAGs
[2022-10-08 08:53:13,431] {logging_mixin.py:109} INFO - [2022-10-08 08:53:13,431] {dag.py:2935} INFO - Setting next_dagrun for Tweets_Dag to 2022-10-08T00:00:00+00:00
[2022-10-08 08:53:13,453] {processor.py:171} INFO - Processing /opt/airflow/dags/TweetsDag.py took 1.778 seconds
